### ISSUE TITLE
Sync Mod Order not working

### ISSUE THREAD

**Issue by TirigonX** [deorder/mo2-plugins#12]
Whenever I try to sync mod order I get this error message in MO (using latest version 2.2.0):
'charmap' codec can't encode character '\ufeff' in position 14: character maps to <undefined>

Any idea what that means?

edit: after "to" it should say "undefined" but with smaller than/greater signs than instead of "". apparently it got removed by the formatting here

**Comment by deorder** [comment]
Can you send me your `modlist.txt`?

**Comment by TirigonX** [comment]
https://pastebin.com/ZrdwEpkq

**Comment by Grogwort** [comment]
I was getting the same error. 
Fixed my local install by editing line 145 in: data/deorder/syncModOrder.py
and changing:
with open(modListPath, 'w') as modListFile:
To:
with open(modListPath, 'w', encoding='utf-8') as modListFile:

Works again!

**Comment by deorder** [comment]
> I was getting the same error.
> Fixed my local install by editing line 145 in: data/deorder/syncModOrder.py
> and changing:
> with open(modListPath, 'w') as modListFile:
> To:
> with open(modListPath, 'w', encoding='utf-8') as modListFile:
> 
> Works again!

Thanks, this saves me some time
