### ISSUE TITLE
Use the optional plugins feature of MO to hide plugins

### ISSUE THREAD

**Issue by ghost** [deorder/mo2-plugins#2]
It moves the plugins to a `optional` folder.

**Comment by Freso** [comment]
But doing this would effectively not make it possible to re-run Merge Plugins, unless I'm misunderstanding something.

**Comment by ghost** [comment]
MP can be re-run, I hide and unhide plugins like that all the time.

**Comment by deorder** [comment]
This feature as discussed on Discord should make it possible for `merge plugins hide` to move plugins in and out of `Optional` instead of adding / removing `.mohidden` to hide plugin. This can be configured inside the mo2 plugin settings (the same place where mo2 plugins can be enabled / disabled)

**Comment by deorder** [comment]
Fixed in commit: https://github.com/deorder/mo2-plugins/commit/c2e32f2adb831e716e5235371e57bbec0cd25bc0
