### ISSUE TITLE
folder name prevents module from being loaded

### ISSUE THREAD

**Issue by cathasachcoireall** [deorder/mo2-plugins#23]
upon opening MO2:

"failed to intialize plugin
.../pugins/mo2-plugins-1.2: ModuleNotFoundError: NO module name 'mo2-plugins-1'"

it seems that the period in the folder name is the problem, I removed it and there was no error, and so the plugin showed up in the tool plugins folder

**Comment by deorder** [comment]
Yeah, it is best to rename the extracted folder to something like `deorder`. I updated the readme to reflect this. Thank you for the report.
