### ISSUE TITLE
Sync Mod Order doesn't sync mod order

### ISSUE THREAD

**Issue by Freso** [deorder/mo2-plugins#3]
I wanted to test that Sync Mod Order was working, so I copied one profile ("John Lee Smith (new)") to a new profile ("JLS test") and changed position of one mod (Audio Tweaks) and then tried to `Sync Mod Order` → choose other profile → `Refresh` → `Close`. After this, neither of the profiles had had the position of Audio Tweaks changed to the other.

[John Lee Smith (new)/modlist.txt](https://github.com/deorder/mo2-plugins/files/2237397/modlist.txt)
[JLS test/modlist.txt](https://github.com/deorder/mo2-plugins/files/2237401/modlist.txt)

**Comment by Freso** [comment]
After poking around the code a bit, I realised I need to right-click on the profiles in the window to get the "Sync mod order" right-click menu option… and that seems to work perfectly. Sorry about the noise!

**Comment by deorder** [comment]
Aha. No problem.

**Comment by AmberOakheart** [comment]
Just wanted to leave a reply Thanking you for this. I've been trying to figure out how to sync the mod order between profiles and couldn't figure it out, been doing it very slowly manually lol. Never thought it would be right click option! >.> makes sense thought!

**Comment by toguspyder** [comment]
This does not seem to work for me. could we get a quick walkthrough on using it. I'm doing the right click then refresh, but nothing seems to be doing anything.

**Comment by AmberOakheart** [comment]
@toguspyder click on the tools (puzzle pieces) and select "synch mod order" while you are currently in the profile that you want others to look like. Then right click on the other profiles and select "synch mod order". do this for all the profiles you want to be in the same order as the profile you are currently loaded in. Thats it :)
