### ISSUE TITLE
Crashs MO2 when I try to use it

### ISSUE THREAD

**Issue by tfretwell** [deorder/mo2-plugins#7]
This plugin was working fine then, when I tried to access it via the tools, MO2 crashed. It kept doing that every couple merges and now it just flat out crashes when I try to use it.

**Comment by deorder** [comment]
This used to be an issue with the old MO2. Are you using the latest MO2? If you are, can you send met the crash dump?

**Comment by tfretwell** [comment]
I am using 2.1.6 pre-alpha.

I can send you the crash dump the next time it happens

**Comment by deorder** [comment]
It was fixed in the public 2.1.6 release. So I will close this ;)
