### ISSUE TITLE
Thanks and a suggestion

### ISSUE THREAD

**Issue by twizz0r** [deorder/mo2-plugins#9]
Just wanted to say "THANK YOU!" for merged plugins hide. It's a godsend and I can't say enough good things about it :) 

Suggestion: Add instructions to remove plugin_python.dll from MO2's blacklist if it exists there. Its there by default on 2.2b8.

**Comment by deorder** [comment]
Thank you. I do not understand? I am not doing anything with `plugin_python.dll`. It is not part of my code, but MO2.

**Comment by twizz0r** [comment]
Correct. May just add that to your install notes? I installed your plugins 4 or 5 times thinking i had done it wrong when all i had to do was remove plugin_python.dll from MO2's black list. LD was the who pointed it out to me.

**Comment by deorder** [comment]
Why was it even on MO2's blacklist :\\
I will ask LD
